
     # Небольшой make-файл для удаления
     # лишних файлов в текущей директории.

     .SILENT :

     .ALL : run

     run :
	      bash gen.sh

     clean :
	        rm -f *.bdf *.tbl *.KEY *.info* *.ima *.ps *.plt *.fit
